language: csharp
solution: AutoBackUp.sln
mono:
 - latest
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore AutoBackUp.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release AutoBackUp.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Core.Tests/bin/Release/Core.Tests.dll