
// This file has been generated by the GUI designer. Do not modify.
namespace GUI
{
	public partial class AddDrive
	{
		private global::Gtk.HPaned hpaned5;

		private global::Gtk.Frame frame6;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView lstAvailableDrives;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Button btnAddFolder;

		private global::Gtk.Button btnRemoveFolder;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.NodeView dgvFolders;

		private global::Gtk.Button btnCancel;

		private global::Gtk.Button btnOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GUI.AddDrive
			this.Name = "GUI.AddDrive";
			this.Title = global::Mono.Unix.Catalog.GetString("Configure New Drive");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child GUI.AddDrive.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hpaned5 = new global::Gtk.HPaned();
			this.hpaned5.CanFocus = true;
			this.hpaned5.Name = "hpaned5";
			this.hpaned5.Position = 217;
			// Container child hpaned5.Gtk.Paned+PanedChild
			this.frame6 = new global::Gtk.Frame();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.lstAvailableDrives = new global::Gtk.TreeView();
			this.lstAvailableDrives.CanFocus = true;
			this.lstAvailableDrives.Name = "lstAvailableDrives";
			this.GtkScrolledWindow.Add(this.lstAvailableDrives);
			this.GtkAlignment2.Add(this.GtkScrolledWindow);
			this.frame6.Add(this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Available Drives</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel2;
			this.hpaned5.Add(this.frame6);
			global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned5[this.frame6]));
			w5.Resize = false;
			// Container child hpaned5.Gtk.Paned+PanedChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.btnAddFolder = new global::Gtk.Button();
			this.btnAddFolder.CanFocus = true;
			this.btnAddFolder.Name = "btnAddFolder";
			this.btnAddFolder.UseUnderline = true;
			this.btnAddFolder.Label = global::Mono.Unix.Catalog.GetString("Add Folder");
			this.hbox8.Add(this.btnAddFolder);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.btnAddFolder]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.btnRemoveFolder = new global::Gtk.Button();
			this.btnRemoveFolder.Sensitive = false;
			this.btnRemoveFolder.CanFocus = true;
			this.btnRemoveFolder.Name = "btnRemoveFolder";
			this.btnRemoveFolder.UseUnderline = true;
			this.btnRemoveFolder.Label = global::Mono.Unix.Catalog.GetString("Remove Folder");
			this.hbox8.Add(this.btnRemoveFolder);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.btnRemoveFolder]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox6.Add(this.hbox8);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox8]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.dgvFolders = new global::Gtk.NodeView();
			this.dgvFolders.CanFocus = true;
			this.dgvFolders.Name = "dgvFolders";
			this.GtkScrolledWindow1.Add(this.dgvFolders);
			this.vbox6.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.GtkScrolledWindow1]));
			w10.Position = 1;
			this.hpaned5.Add(this.vbox6);
			w1.Add(this.hpaned5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(w1[this.hpaned5]));
			w12.Position = 0;
			// Internal child GUI.AddDrive.ActionArea
			global::Gtk.HButtonBox w13 = this.ActionArea;
			w13.Name = "dialog1_ActionArea";
			w13.Spacing = 10;
			w13.BorderWidth = ((uint)(5));
			w13.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnCancel = new global::Gtk.Button();
			this.btnCancel.CanDefault = true;
			this.btnCancel.CanFocus = true;
			this.btnCancel.Name = "btnCancel";
			this.btnCancel.UseStock = true;
			this.btnCancel.UseUnderline = true;
			this.btnCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.btnCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w13[this.btnCancel]));
			w14.Expand = false;
			w14.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnOk = new global::Gtk.Button();
			this.btnOk.Sensitive = false;
			this.btnOk.CanDefault = true;
			this.btnOk.CanFocus = true;
			this.btnOk.Name = "btnOk";
			this.btnOk.UseStock = true;
			this.btnOk.UseUnderline = true;
			this.btnOk.Label = "gtk-ok";
			this.AddActionWidget(this.btnOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w13[this.btnOk]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 627;
			this.DefaultHeight = 346;
			this.Show();
			this.btnCancel.Clicked += new global::System.EventHandler(this.CloseDialog);
		}
	}
}
